#pragma config(Hubs,  S1, HTMotor,  HTMotor,  none,     none)
#pragma config(Hubs,  S4, HTServo,  HTMotor,  none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     ,               sensorTouch)
#pragma config(Sensor, S3,     ,               sensorCOLORFULL)
#pragma config(Sensor, S4,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     clawMotor,     tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C1_2,     rightWheel,    tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     leftWheel,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_1,     bar1,          tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S4_C2_2,     bar2,          tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S4_C1_1,    flag,                 tServoStandard)
#pragma config(Servo,  srvo_S4_C1_2,    clawServoLeft,        tServoStandard)
#pragma config(Servo,  srvo_S4_C1_3,    clawServoRight,       tServoStandard)
#pragma config(Servo,  srvo_S4_C1_4,    barServoLeft,         tServoNone)
#pragma config(Servo,  srvo_S4_C1_5,    barServoRight,        tServoNone)
#pragma config(Servo,  srvo_S4_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma DebuggerWindows("joystickGame")
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                           Tele-Operation Mode Code Template
//
// This file contains a template for simplified creation of an tele-op program for an FTC
// competition.
//
// You need to customize two functions with code unique to your specific robot.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

const int MOTOR_SCALAR = -128;
const int POWER1 = 10;
const int POWER2 = 100;
bool basketFlat = false;
bool correcting = true;
bool correction = true;
const int THRESHOLD = 10;
bool backupController = false;


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                    initializeRobot
//
// Prior to the start of tele-op mode, you may want to perform some initialization on your robot
// and the variables within your program.
//
// In most cases, you may not have to add any code to this function and it will remain "empty".
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

void initializeRobot()
{
	// Place code here to sinitialize servos to starting positions.
	// Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.

	return;
}


/////////////////////////////////////////////////////////////////////////////////////////////////////
//
//                                         Main Task
//
// The following is the main code for the tele-op robot operation. Customize as appropriate for
// your specific robot.
//
// Game controller / joystick information is sent periodically (about every 50 milliseconds) from
// the FMS (Field Management System) to the robot. Most tele-op programs will follow the following
// logic:
//   1. Loop forever repeating the following actions:
//   2. Get the latest game controller / joystick settings that have been received from the PC.
//   3. Perform appropriate actions based on the joystick + buttons settings. This is usually a
//      simple action:
//      *  Joystick values are usually directly translated into power levels for a motor or
//         position of a servo.
//      *  Buttons are usually used to start/stop a motor or cause a servo to move to a specific
//         position.
//   4. Repeat the loop.
//
// Your program needs to continuously loop because you need to continuously respond to changes in
// the game controller settings.
//
// At the end of the tele-op period, the FMS will autonmatically abort (stop) execution of the program.
//
/////////////////////////////////////////////////////////////////////////////////////////////////////

task main()
{
	initializeRobot();

	waitForStart();   // wait for start of tele-op phase

	while (true)
	{
		///////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////
		////                                                   ////
		////      Add your robot specific tele-op code here.   ////
		////                                                   ////
		///////////////////////////////////////////////////////////
		///////////////////////////////////////////////////////////

		// Insert code to have servos and motors respond to joystick and button values.

		// Look in the ROBOTC samples folder for programs that may be similar to what you want to perform.
		// You may be able to find "snippets" of code that are similar to the functions that you want to
		// perform.

		clearDebugStream();
		writeDebugStream("Power On");
		while(true)
		{


			if (joy2Btn(10))
			{
				backupController = true;
			}
			if (joy2Btn(9))
			{
				backupController = false;
			}


			if (joy1Btn(9))
			{
				backupController = true;
			}
			if (joy1Btn(10))
			{
				backupController = false;
			}

			if (backupController)
			{
				writeDebugStreamLine("backup");
			}
			else
			{
				writeDebugStreamLine("primary");
			}
			getJoystickSettings(joystick);  // Update Buttons and Joysticks

			/*
			Maps joy1 (the left one) to both motors.
			*/
			if (!backupController)
			{
				if ((abs(joystick.joy1_x2) > THRESHOLD) || (abs(joystick.joy1_y2) > THRESHOLD))
				{
					motor[leftWheel] =  (((float)joystick.joy1_y2/MOTOR_SCALAR) - ((float)joystick.joy1_x2/MOTOR_SCALAR))*100;
					motor[rightWheel] = (((float)joystick.joy1_y2/MOTOR_SCALAR) + ((float)joystick.joy1_x2/MOTOR_SCALAR))*100;
				}
				else
				{
					motor[leftWheel] = 0;
					motor[rightWheel] = 0;
				}
				if (joy1Btn(1))
				{
					writeDebugStreamLine("Flag Servo");
					if(servo[flag]!=220)
					{
						servo[flag] = 220;
					}
					else
					{
						servo[flag] = 18;
					}
					wait1Msec(500);
				}

				/*********************************************************
				----------------------Flag Turner-------------------------
				*********************************************************/

				int tophat = joystick.joy1_TopHat;


				if (joy1Btn(2))
				{
					writeDebugStreamLine("Flag Motor");
					motor[flagMotor] = 100;
				}
				else if (joy1Btn(4))
				{
					motor[flagMotor] = -100;
				}
				else if (tophat == 0)
				{
					motor[flagMotor] = 10;
				}
				else if (tophat == 4)
				{
					motor[flagMotor] = -10;
				}
				else if (tophat==2)
				{
					servo[clawServoRight] += 1;
					servo[clawServoLeft] -= 1;
					wait1Msec(10);
				}
				else if (tophat == 6)
				{
					servo[clawServoRight] -= 1;
					servo[clawServoLeft] += 1;
					wait1Msec(10);
				}
				else
				{
					motor[flagMotor] = 0;
				}

				/******************
				Flag
				******************/
				if (joy1Btn(8))
				{
					writeDebugStreamLine("Claw Motor +");
					motor[clawMotor] = -50;
				}
				else if (joy1Btn(6))
				{
					writeDebugStreamLine("Claw Motor +");
					motor[clawMotor] = 50;
				}
				else
				{
					bFloatDuringInactiveMotorPWM = false;

					motor[clawMotor] = 0;
				}

				/******
				Claw
				******/
				if (joy1Btn(7))
				{
					writeDebugStreamLine("Claw Servo +");
					servo[clawServoLeft] = 70;
					servo[clawServoRight] = 136;
				}

				if (joy1Btn(5))
				{
					writeDebugStreamLine("Claw Servo +");
					servo[clawServoLeft] = 212;
					servo[clawServoRight] = 6;

				}

				if (joy1Btn(3))
				{
					if (servo[barServoRight] != 128)
					{
						servo[barServoLeft] = 101;
						servo[barServoRight] = 128;
					}
					else
					{
						servo[barServoLeft] = 255;
						servo[barServoRight] = 0;
					}
					wait1Msec(500);
				}


				//Raise and Lower Hanging Bar
				if(joystick.joy1_y1 > 5)
				{
					motor[bar1] = joystick.joy1_y1;
					motor[bar2] = joystick.joy1_y1;
				}
				else if (joystick.joy1_y1 < 5)
				{
					motor[bar1] = joystick.joy1_y1;
					motor[bar2] = joystick.joy1_y1;
				}

			}

			/**********************************Joystick 2*******************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			***********************************Joystick 2*******************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			****************************************************************************************
			**********************************Joystick 2******************************************/
			else
			{/*
				Maps joy1 (the left one) to both motors.
				*/
				if ((abs(joystick.joy2_x2) > THRESHOLD) || (abs(joystick.joy2_y2) > THRESHOLD))
				{
					motor[leftWheel] =  (((float)joystick.joy2_y2/MOTOR_SCALAR) - ((float)joystick.joy2_x2/MOTOR_SCALAR))*100;
					motor[rightWheel] = (((float)joystick.joy2_y2/MOTOR_SCALAR) + ((float)joystick.joy2_x2/MOTOR_SCALAR))*100;
				}
				else
				{
					motor[leftWheel] = 0;
					motor[rightWheel] = 0;
				}
				if (joy2Btn(1))
				{
					writeDebugStreamLine("Flag Servo");
					if(servo[flag]!=220)
					{
						servo[flag] = 220;
					}
					else
					{
						servo[flag] = 18;
					}
					wait1Msec(500);
				}

				/*********************************************************
				----------------------Flag Turner-------------------------
				*********************************************************/

				int tophat = joystick.joy2_TopHat;


				if (joy2Btn(2))
				{
					writeDebugStreamLine("Flag Motor");
					motor[flagMotor] = 100;
				}
				else if (joy2Btn(4))
				{
					motor[flagMotor] = -100;
				}
				else if (tophat == 0)
				{
					motor[flagMotor] = 10;
				}
				else if (tophat == 4)
				{
					motor[flagMotor] = -10;
				}
				else if (tophat==2)
				{
					servo[clawServoRight] += 1;
					servo[clawServoLeft] -= 1;
					wait1Msec(10);
				}
				else if (tophat == 6)
				{
					servo[clawServoRight] -= 1;
					servo[clawServoLeft] += 1;
					wait1Msec(10);
				}
				else
				{
					motor[flagMotor] = 0;
				}

				/******************
				Flag
				******************/
				if (joy2Btn(8))
				{
					writeDebugStreamLine("Claw Motor +");
					motor[clawMotor] = -50;
				}
				else if (joy2Btn(6))
				{
					writeDebugStreamLine("Claw Motor +");
					motor[clawMotor] = 50;
				}
				else
				{
					bFloatDuringInactiveMotorPWM = false;

					motor[clawMotor] = 0;
				}

				/******
				Claw
				******/
				if (joy2Btn(7))
				{
					writeDebugStreamLine("Claw Servo +");
					servo[clawServoLeft] = 70;
					servo[clawServoRight] = 136;
				}

				if (joy2Btn(5))
				{
					writeDebugStreamLine("Claw Servo +");
					servo[clawServoLeft] = 212;
					servo[clawServoRight] = 6;

				}


				//Raise and Lower Hanging Bar
				if(joystick.joy1_y2 > 5)
				{
					motor[bar1] = joystick.joy2_y1;
					motor[bar2] = joystick.joy2_y1;
				}
				else if (joystick.joy1_y2 < 5)
				{
					motor[bar1] = joystick.joy2_y1;
					motor[bar2] = joystick.joy2_y1;
				}

				if (joy2Btn(3))
				{
					if (servo[barServoRight] != 128)
					{
						servo[barServoLeft] = 101;
						servo[barServoRight] = 128;
					}
					else
					{
						servo[barServoLeft] = 255;
						servo[barServoRight] = 0;
					}
					wait1Msec(500);
				}
			}
		}
	}
}
